version: '3'
services:
  gekko:
    restart: always
    image: butarem/gekko:stable
    volumes:
      - ./volumes/gekko/history:/usr/src/app/history
      - ./config.js:/usr/src/app/config.js
      - ./config.js:/usr/src/app/web/routes/baseConfig.js
    links:
      - redis
      - mongodb
    environment:
     - HOST
     - PORT
    ports: # you can comment this out when using the nginx frontend
    - "${PORT}:${PORT}"
    expose:
    - "${PORT}"
## optionally set nginx vars if you wish to frontend it with nginx
#    environment:
#     - VIRTUAL_HOST=gekko
#     - PORT=3000
#     - DOMAIN=gekko

  redis:
    image: redis:latest
    volumes:
      - ./volumes/redis:/data

## optionally uncomment if you wish to use postgresql as a db
  mongodb:
    image: mongo:latest
    volumes:
      - ./volumes/mongodb:/data/db
